# Generated by Django 5.1.6 on 2025-04-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korea', '0002_alter_korea_url'),
    ]

    operations = [
    ]
