# Generated by Django 5.1.6 on 2025-04-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korea', '0005_alter_korea_end_price_alter_korea_start_price'),
        ('korea', '0005_merge_0003_auto_20250403_1736_0004_auto_20250403_1631'),
    ]

    operations = [
    ]
