# Generated by Django 5.1.6 on 2025-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korea', '0006_merge_20250404_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='korea',
            name='drive_type',
            field=models.CharField(choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный'), ('plug_in', 'Подключаемый')], default=1, max_length=20, verbose_name='Привод'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='korea',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, help_text='Введите объем двигателя в литрах, например: 4.4', max_digits=3, verbose_name='Объем двигателя (л)'),
        ),
        migrations.AlterField(
            model_name='korea',
            name='mileage',
            field=models.PositiveIntegerField(db_index=True, help_text='Введите пробег автомобиля в километрах, например: 100000', verbose_name='Пробег (км)'),
        ),
        migrations.AlterField(
            model_name='korea',
            name='power',
            field=models.PositiveIntegerField(help_text='Введите мощность двигателя в лошадиных силах, например: 150', verbose_name='Мощность (л.с.)'),
        ),
    ]
