# Generated by Django 5.1.6 on 2025-04-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_interior_seat_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
    ]
