# Generated by Django 5.1.6 on 2025-04-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0003_auto_20250403_1627'),
    ]

    operations = [
    ]
