# Generated by Django 5.1.6 on 2025-03-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='America',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Объем двигателя (л)')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность (л.с.)')),
                ('configuration', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электрический'), ('hydrogen', 'Водород')], max_length=20, verbose_name='Тип топлива')),
                ('transmission_type', models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая'), ('robot', 'Роботизированная'), ('variator', 'Вариатор'), ('dsg', 'DSG (Робот с двойным сцеплением)')], max_length=20, verbose_name='Тип КПП')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Начальная цена')),
                ('end_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Конечная цена')),
                ('auction_start_time', models.DateTimeField(verbose_name='Время начала аукциона')),
                ('url', models.URLField(verbose_name='Ссылка на машину')),
            ],
            options={
                'verbose_name': 'Автомобиль из Америки',
                'verbose_name_plural': 'Автомобили из Америки',
            },
        ),
    ]
