# Generated by Django 5.1.6 on 2025-04-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='america',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на машину'),
        ),
    ]
