# Generated by Django 5.1.6 on 2025-03-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0003_alter_america_auction_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='america',
            name='mileage',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Пробег (км)'),
        ),
        migrations.AlterField(
            model_name='america',
            name='start_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='america',
            name='year',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Год выпуска'),
        ),
        migrations.CreateModel(
            name='ComparisonsAmerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparisons', models.BooleanField(default=False, verbose_name='Сравнение')),
                ('america_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='america_cars', to='america.america', verbose_name='Америка:')),
            ],
            options={
                'verbose_name': 'Сравнение Америка',
                'verbose_name_plural': 'Сравнение Америка',
            },
        ),
    ]
