# Generated by Django 5.1.6 on 2025-04-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0003_alter_america_url'),
    ]

    operations = [
    ]
