# Generated by Django 5.1.6 on 2025-04-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0004_auto_20250403_1736'),
        ('america', '0005_auto_20250403_1630'),
    ]

    operations = [
    ]
