# Generated by Django 5.1.6 on 2025-04-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('america', '0006_alter_america_end_price_alter_america_start_price'),
        ('america', '0006_merge_0004_auto_20250403_1736_0005_auto_20250403_1630'),
    ]

    operations = [
    ]
